export const GET_USER = "GET_USER";
export const GET_USER_ID = "GET_USER_ID";
export const DELETE_USER = "DELETE_USER";
export const GET_NAMES = "GET_NAMES";
export const GET_DETAILS = "GET_DETAILS";
export const GET_PETS = "GET_PETS";
export const DELETE_PET = "DELETE_PET";
export const RESET_DETAILS = "RESET_DETAILS";
export const POST_PET = "POST_PET";
export const POST_USER = "POST_USER";
export const ORDER_BY_AGE = "ORDER_BY_AGE";
export const FILTER_BY_SIZE = "FILTER_BY_SIZE";
export const FILTER_BY_LOCATION = "FILTER_BY_LOCATION";
export const FILTER_BY_SEX = "FILTER_BY_SEX";
export const GET_TYPES = 'GET_TYPES'
export const GET_CATS = 'GET_CATS'
export const FULL_FILTER_AGE="FULL_FILTER_AGE"
export const FULL_FILTER_SEX="FULL_FILTER_SEX"
export const NO_FILTER_PETS="NO_FILTER_PETS"
export const FULL_FILTER_LOCATION="FULL_FILTER_LOCATION"
export const FULL_FILTER_SIZE="FULL_FILTER_SIZE"
export const GET_LOCATION="GET_LOCATION"